cloud:
  aws:
    credentials:
      access-key: AKIAQMKBQOSM5OHQGQVE
      secret-key: 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
    region:
      static: us-west-2
    stack:
      auto: false

application:
  bucket:
    name: atypontube


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 50MB
      max-request-size: 60MB

server:
  port: 8084